language: android
jdk: oraclejdk8

env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # 8 minutes (2 minutes by default)

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-24.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew checkstyle assemble testDebug